server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafe
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org.hibernate.sql: debug